[package]
name = "mumrik"
version = "0.1.0"
authors = ["akitsu <akitsu.sanae@gmail.com>"]

[dependencies]
peg = "0.6.2"
lazy_static = "1.4.0"
nf2llvmir = { git = "https://github.com/akitsu-sanae/nf2llvmir" }

